const dotenv = require('dotenv');
const User = require('./models/User');
const Product = require('./models/Product');
const connectDB = require('./config/db');

dotenv.config();
connectDB();

const products = [
  // UI/UX & Templates
  { name: 'Modern UI Kit Pro', image: 'https://images.unsplash.com/photo-1586717791821-3f44a563eb4c?auto=format&fit=crop&q=80&w=800', description: 'Complete UI kit with 200+ components, 15 pre-built templates, and interactive prototypes. Perfect for SaaS applications.', price: 89.00, originalPrice: 133.50, category: 'Templates', fileUrl: 'https://example.com/download/modern-ui-kit.zip' },
  { name: 'E-Commerce Figma Template', image: 'https://images.unsplash.com/photo-1559526324-4b87b5e36e44?auto=format&fit=crop&q=80&w=800', description: 'Full e-commerce Figma UI kit with 80+ screens, auto-layout components, and dark/light mode support.', price: 49.00, originalPrice: 79.00, category: 'Templates', fileUrl: 'https://example.com/download/ecom-figma.zip' },
  { name: 'Dashboard Admin Pro', image: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&q=80&w=800', description: 'Premium admin dashboard template with 6 unique layouts, 40+ widgets, and chart components.', price: 59.00, originalPrice: 99.00, category: 'Templates', fileUrl: 'https://example.com/download/dashboard-admin.zip' },
  { name: 'Mobile App UI Bundle', image: 'https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?auto=format&fit=crop&q=80&w=800', description: 'A stunning bundle of 5 complete mobile app UI kits: fitness, food delivery, finance, travel, and social media.', price: 119.00, originalPrice: 199.00, category: 'Templates', fileUrl: 'https://example.com/download/mobile-bundle.zip' },
  { name: 'Landing Page Kit', image: 'https://images.unsplash.com/photo-1467232004584-a241de8bcf5d?auto=format&fit=crop&q=80&w=800', description: '20 beautifully crafted landing page templates for SaaS, agencies, portfolios, and product launches.', price: 39.00, originalPrice: 65.00, category: 'Templates', fileUrl: 'https://example.com/download/landing-kit.zip' },

  // Graphics
  { name: 'Abstract 3D Icon Pack', image: 'https://images.unsplash.com/photo-1633356122544-f134324a6cee?auto=format&fit=crop&q=80&w=800', description: 'A beautiful collection of 50+ abstract 3D icons for web and mobile. Includes high-resolution PNGs and source files.', price: 29.99, originalPrice: 44.98, category: 'Graphics', fileUrl: 'https://example.com/download/abstract-3d-icons.zip' },
  { name: 'Brand Identity Pack', image: 'https://images.unsplash.com/photo-1493421419110-74f4e85ba126?auto=format&fit=crop&q=80&w=800', description: 'Everything you need to launch a professional brand: logos, business card templates, letterheads, and brand guidelines.', price: 69.00, originalPrice: 120.00, category: 'Graphics', fileUrl: 'https://example.com/download/brand-identity.zip' },
  { name: 'Social Media Template Bundle', image: 'https://images.unsplash.com/photo-1611162617213-7d7a39e9b1d7?auto=format&fit=crop&q=80&w=800', description: '150+ Instagram, Facebook, Twitter, and LinkedIn post templates. Fully editable in Canva and Photoshop.', price: 24.00, originalPrice: 40.00, category: 'Graphics', fileUrl: 'https://example.com/download/social-media-bundle.zip' },
  { name: 'Illustration Vector Pack', image: 'https://images.unsplash.com/photo-1580541631971-1f6a46bc6b01?auto=format&fit=crop&q=80&w=800', description: '80+ unique vector illustrations in flat design style. Available in SVG, PNG, and AI formats.', price: 34.00, originalPrice: 58.00, category: 'Graphics', fileUrl: 'https://example.com/download/illustration-pack.zip' },
  { name: 'Gradient Background Pack', image: 'https://images.unsplash.com/photo-1541701494587-cb58502866ab?auto=format&fit=crop&q=80&w=800', description: '200+ unique gradient backgrounds in 4K resolution. Perfect for websites, apps, and print projects.', price: 14.00, originalPrice: 25.00, category: 'Graphics', fileUrl: 'https://example.com/download/gradients.zip' },

  // Audio
  { name: 'Lo-Fi Beats Sample Pack', image: 'https://images.unsplash.com/photo-1516280440614-37939bbacd81?auto=format&fit=crop&q=80&w=800', description: '500 MB of high-quality lo-fi beats, drum loops, and atmospheric textures. Royalty-free.', price: 15.50, originalPrice: 23.25, category: 'Audio', fileUrl: 'https://example.com/download/lo-fi-beats.zip' },
  { name: 'Epic Cinematic Soundtrack', image: 'https://images.unsplash.com/photo-1598488035139-bdbb2231ce04?auto=format&fit=crop&q=80&w=800', description: '30 epic cinematic BGM tracks ideal for trailers, YouTube, games, and presentations. 320kbps MP3 + WAV.', price: 29.00, originalPrice: 49.00, category: 'Audio', fileUrl: 'https://example.com/download/cinematic-ost.zip' },
  { name: 'Podcast Intro Pack', image: 'https://images.unsplash.com/photo-1478737270197-b239a9fcaaf1?auto=format&fit=crop&q=80&w=800', description: '10 professional podcast intro/outro jingles and transitions. Perfect for branding your show.', price: 19.00, originalPrice: 32.00, category: 'Audio', fileUrl: 'https://example.com/download/podcast-intro.zip' },
  { name: 'UI Sound Effects Kit', image: 'https://images.unsplash.com/photo-1614149162883-504ce4d13909?auto=format&fit=crop&q=80&w=800', description: '200+ UI sound effects including notification beeps, button clicks, transitions, and alerts for apps & games.', price: 22.00, originalPrice: 36.00, category: 'Audio', fileUrl: 'https://example.com/download/ui-sfx.zip' },

  // Photography
  { name: 'Minimalist Lightroom Presets', image: 'https://images.unsplash.com/photo-1493612276216-ee3925520721?auto=format&fit=crop&q=80&w=800', description: 'Give your photos a clean, professional look with these 12 Lightroom presets. For desktop and mobile.', price: 12.00, originalPrice: 18.00, category: 'Photography', fileUrl: 'https://example.com/download/minimal-presets.zip' },
  { name: 'Moody Film Presets Pack', image: 'https://images.unsplash.com/photo-1510915361894-db8b60106cb1?auto=format&fit=crop&q=80&w=800', description: '20 moody film-inspired Lightroom presets for portrait, landscape, and street photography.', price: 18.00, originalPrice: 30.00, category: 'Photography', fileUrl: 'https://example.com/download/moody-film.zip' },
  { name: 'Stock Photo Mega Bundle', image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?auto=format&fit=crop&q=80&w=800', description: '500 curated royalty-free stock photos across 10 categories. High-resolution (5000px+). Commercial license included.', price: 39.00, originalPrice: 69.00, category: 'Photography', fileUrl: 'https://example.com/download/stock-bundle.zip' },

  // Fonts & Typography
  { name: 'Premium Font Collection', image: 'https://images.unsplash.com/photo-1636051028886-0059ad2383c8?auto=format&fit=crop&q=80&w=800', description: '25 professionally crafted font families including serifs, sans-serifs, and display fonts. OTF + TTF + WOFF2.', price: 45.00, originalPrice: 89.00, category: 'Fonts', fileUrl: 'https://example.com/download/font-collection.zip' },
  { name: 'Handwritten Script Bundle', image: 'https://images.unsplash.com/photo-1455541504462-57ebb2a9cec1?auto=format&fit=crop&q=80&w=800', description: '10 beautiful handwritten and brush script fonts for personal and commercial use. Great for logos and invitations.', price: 22.00, originalPrice: 40.00, category: 'Fonts', fileUrl: 'https://example.com/download/script-fonts.zip' },

  // Code & Dev
  { name: 'React Component Library', image: 'https://images.unsplash.com/photo-1633356122102-3fe601e05bd2?auto=format&fit=crop&q=80&w=800', description: '100+ production-ready React components built with Tailwind CSS. Includes Storybook docs and TypeScript support.', price: 79.00, originalPrice: 129.00, category: 'Code', fileUrl: 'https://example.com/download/react-components.zip' },
  { name: 'Next.js SaaS Boilerplate', image: 'https://images.unsplash.com/photo-1555066931-4365d14bab8c?auto=format&fit=crop&q=80&w=800', description: 'Full-stack SaaS starter with Next.js 14, authentication, Stripe payments, prisma DB, and dashboard.', price: 149.00, originalPrice: 249.00, category: 'Code', fileUrl: 'https://example.com/download/nextjs-saas.zip' },
  { name: 'Python Automation Scripts', image: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?auto=format&fit=crop&q=80&w=800', description: '30 ready-to-use Python automation scripts for data scraping, file management, email automation, and more.', price: 35.00, originalPrice: 59.00, category: 'Code', fileUrl: 'https://example.com/download/python-scripts.zip' },

  // Video
  { name: 'Motion Graphics Pack', image: 'https://images.unsplash.com/photo-1574717024453-46e75a35d38d?auto=format&fit=crop&q=80&w=800', description: '50 After Effects motion graphics templates for YouTube intros, logos reveals, and lower thirds.', price: 55.00, originalPrice: 89.00, category: 'Video', fileUrl: 'https://example.com/download/motion-graphics.zip' },
  { name: 'LUTs Color Grading Pack', image: 'https://images.unsplash.com/photo-1492724441997-5dc865305da7?auto=format&fit=crop&q=80&w=800', description: '40 cinematic LUTs for video color grading. Compatible with Premiere Pro, Final Cut, DaVinci Resolve.', price: 25.00, originalPrice: 45.00, category: 'Video', fileUrl: 'https://example.com/download/luts-pack.zip' },

  // ──────────────────────────────────────────────────
  //  NEW PRODUCTS (35 additional)
  // ──────────────────────────────────────────────────

  // ── Templates (5 new) ──
  { name: 'Portfolio Website Template', image: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=800', description: 'A sleek, minimal portfolio template built for designers, photographers, and freelancers. Includes 12 pages, smooth scroll animations, and a working contact form. Fully responsive with Retina-ready assets.', price: 29.00, originalPrice: 49.00, category: 'Templates', fileUrl: 'https://example.com/download/portfolio-template.zip', badge: 'New' },
  { name: 'Restaurant & Café UI Kit', image: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&q=80&w=800', description: 'Complete Figma UI kit tailored for restaurants, cafés, and food delivery apps. Features 60+ screens including menu cards, table reservations, order tracking, and a loyalty rewards section.', price: 44.00, originalPrice: 75.00, category: 'Templates', fileUrl: 'https://example.com/download/restaurant-ui.zip' },
  { name: 'Blog & Magazine Theme', image: 'https://images.unsplash.com/photo-1499750310107-5fef28a66643?auto=format&fit=crop&q=80&w=800', description: 'Elegant blog and online magazine template with 5 homepage variations, article layouts, category pages, and newsletter signup forms. Built with clean HTML/CSS and optimized for SEO.', price: 35.00, originalPrice: 59.00, category: 'Templates', fileUrl: 'https://example.com/download/blog-magazine.zip', badge: 'Featured' },
  { name: 'Fitness App Wireframe Kit', image: 'https://images.unsplash.com/photo-1476480862126-209bfaa8edc8?auto=format&fit=crop&q=80&w=800', description: '45 wireframe screens for fitness and health tracking apps. Includes workout planner, calorie tracker, progress charts, and social feed modules. Available in Figma and Sketch formats.', price: 25.00, originalPrice: 42.00, category: 'Templates', fileUrl: 'https://example.com/download/fitness-wireframes.zip' },
  { name: 'Crypto & NFT Dashboard', image: 'https://images.unsplash.com/photo-1639762681485-074b7f938ba0?auto=format&fit=crop&q=80&w=800', description: 'Dark-themed dashboard UI kit for cryptocurrency exchanges and NFT marketplaces. Includes wallet overview, trading charts, portfolio analytics, and NFT gallery views with 70+ components.', price: 69.00, originalPrice: 119.00, category: 'Templates', fileUrl: 'https://example.com/download/crypto-dashboard.zip', badge: 'Hot' },

  // ── Graphics (5 new) ──
  { name: 'Isometric Workspace Illustrations', image: 'https://images.unsplash.com/photo-1558655146-9f40138edfeb?auto=format&fit=crop&q=80&w=800', description: '40 isometric vector illustrations depicting modern workspaces, remote teams, and office scenes. Fully editable in Adobe Illustrator and Figma. Includes day and night variations.', price: 32.00, originalPrice: 55.00, category: 'Graphics', fileUrl: 'https://example.com/download/isometric-workspace.zip', badge: 'New' },
  { name: 'Hand-Drawn Doodle Pack', image: 'https://images.unsplash.com/photo-1513364776144-60967b0f800f?auto=format&fit=crop&q=80&w=800', description: '300+ hand-drawn doodle elements including arrows, borders, frames, speech bubbles, and decorative accents. Perfect for presentations, social media posts, and branding projects. SVG + PNG.', price: 18.00, originalPrice: 30.00, category: 'Graphics', fileUrl: 'https://example.com/download/doodle-pack.zip' },
  { name: 'Glassmorphism UI Elements', image: 'https://images.unsplash.com/photo-1557672172-298e090bd0f1?auto=format&fit=crop&q=80&w=800', description: 'A trendy set of 60+ glassmorphism-style UI components — cards, buttons, navigation bars, modals, and form elements. Includes Figma source files with auto-layout and variants.', price: 27.00, originalPrice: 45.00, category: 'Graphics', fileUrl: 'https://example.com/download/glassmorphism-ui.zip', badge: 'Hot' },
  { name: 'Vintage Badge & Logo Creator', image: 'https://images.unsplash.com/photo-1626785774573-4b799315345d?auto=format&fit=crop&q=80&w=800', description: 'Design retro and vintage logos in minutes with this badge creator kit. Contains 50 pre-made badges, 100+ design elements, textures, and ribbons. PSD + AI + EPS formats included.', price: 23.00, originalPrice: 39.00, category: 'Graphics', fileUrl: 'https://example.com/download/vintage-badges.zip' },
  { name: 'Emoji & Sticker Pack', image: 'https://images.unsplash.com/photo-1543807535-eceef0bc6599?auto=format&fit=crop&q=80&w=800', description: '500+ custom emoji and sticker designs in 3D and flat styles. Categories include expressions, food, animals, objects, and gestures. PNG at multiple resolutions + Lottie JSON animations.', price: 36.00, originalPrice: 60.00, category: 'Graphics', fileUrl: 'https://example.com/download/emoji-stickers.zip', badge: 'Bestseller' },

  // ── Audio (5 new) ──
  { name: 'Ambient Nature Soundscapes', image: 'https://images.unsplash.com/photo-1500468756762-a401b6f17b46?auto=format&fit=crop&q=80&w=800', description: '25 immersive ambient soundscapes featuring rain, ocean waves, forest birds, thunderstorms, and flowing streams. Each track is 10+ minutes long. Perfect for meditation apps, ASMR, or background audio. WAV + MP3.', price: 19.00, originalPrice: 32.00, category: 'Audio', fileUrl: 'https://example.com/download/nature-sounds.zip' },
  { name: 'Hip-Hop Drum Kit Pro', image: 'https://images.unsplash.com/photo-1571330735066-03aaa9429d89?auto=format&fit=crop&q=80&w=800', description: 'Industry-standard hip-hop drum kit with 400+ one-shots: kicks, snares, hi-hats, 808s, claps, and percussions. Curated from analog hardware synths. WAV 24-bit/44.1kHz. Royalty-free.', price: 24.00, originalPrice: 40.00, category: 'Audio', fileUrl: 'https://example.com/download/hiphop-drums.zip', badge: 'Hot' },
  { name: 'Corporate Background Music', image: 'https://images.unsplash.com/photo-1497032628192-86f99bcd76bc?auto=format&fit=crop&q=80&w=800', description: '20 uplifting and professional background music tracks for corporate videos, explainer animations, product demos, and company presentations. Multiple lengths per track (15s, 30s, 60s, full).', price: 34.00, originalPrice: 55.00, category: 'Audio', fileUrl: 'https://example.com/download/corporate-bgm.zip', badge: 'Featured' },
  { name: 'Retro Synthwave Collection', image: 'https://images.unsplash.com/photo-1470225620780-dba8ba36b745?auto=format&fit=crop&q=80&w=800', description: '15 retro synthwave and vaporwave tracks with heavy analog synth vibes. Ideal for gaming videos, retro-themed content, and creative projects. Includes stems for remix flexibility.', price: 28.00, originalPrice: 45.00, category: 'Audio', fileUrl: 'https://example.com/download/synthwave.zip' },
  { name: 'Game Audio Essentials', image: 'https://images.unsplash.com/photo-1511512578047-dfb367046420?auto=format&fit=crop&q=80&w=800', description: 'Complete game audio toolkit with 500+ sound effects: power-ups, explosions, footsteps, menu clicks, coins, weapon sounds, and ambient loops. Organized by category. WAV format, loop-ready.', price: 42.00, originalPrice: 69.00, category: 'Audio', fileUrl: 'https://example.com/download/game-audio.zip', badge: 'Bestseller' },

  // ── Photography (5 new) ──
  { name: 'Golden Hour Presets', image: 'https://images.unsplash.com/photo-1495616811223-4d98c6e9c869?auto=format&fit=crop&q=80&w=800', description: '15 warm, golden-hour Lightroom presets that add a rich, sun-kissed tone to your photos. Works beautifully with portraits, lifestyle, and outdoor photography. Desktop + Mobile DNG.', price: 14.00, originalPrice: 24.00, category: 'Photography', fileUrl: 'https://example.com/download/golden-hour.zip', badge: 'New' },
  { name: 'Urban Street Photography Presets', image: 'https://images.unsplash.com/photo-1449824913935-59a10b8d2000?auto=format&fit=crop&q=80&w=800', description: '18 gritty, high-contrast presets designed for urban and street photography. Adds dramatic shadows, desaturated tones, and a cinematic edge. Compatible with Lightroom Classic and CC.', price: 16.00, originalPrice: 28.00, category: 'Photography', fileUrl: 'https://example.com/download/urban-presets.zip' },
  { name: 'Aerial & Drone Photo Bundle', image: 'https://images.unsplash.com/photo-1473968512647-3e447244af8f?auto=format&fit=crop&q=80&w=800', description: '200 stunning aerial and drone photographs captured across mountains, coastlines, cities, and farmlands. 6000px+ resolution with full commercial rights. Perfect for websites, print, and advertising.', price: 49.00, originalPrice: 89.00, category: 'Photography', fileUrl: 'https://example.com/download/aerial-photos.zip', badge: 'Featured' },
  { name: 'Food Photography Preset Pack', image: 'https://images.unsplash.com/photo-1476224203421-9ac39bcb3327?auto=format&fit=crop&q=80&w=800', description: '12 mouth-watering Lightroom presets specifically tuned for food and recipe photography. Enhances colors, sharpens textures, and adds a warm, appetizing glow. Includes before/after samples.', price: 11.00, originalPrice: 19.00, category: 'Photography', fileUrl: 'https://example.com/download/food-presets.zip' },
  { name: 'Black & White Masterclass Presets', image: 'https://images.unsplash.com/photo-1500051638674-ff996a0ec29e?auto=format&fit=crop&q=80&w=800', description: '10 premium black & white Lightroom presets inspired by classic darkroom techniques. Includes high-contrast, matte, grain, and split-tone variations. Perfect for fine art and editorial work.', price: 13.00, originalPrice: 22.00, category: 'Photography', fileUrl: 'https://example.com/download/bw-presets.zip' },

  // ── Fonts (5 new) ──
  { name: 'Modern Sans-Serif Pack', image: 'https://images.unsplash.com/photo-1561070791-2526d30994b5?auto=format&fit=crop&q=80&w=800', description: '8 clean, geometric sans-serif font families with 6 weights each (Thin to Black). Ideal for headings, branding, and UI design. Includes web fonts (WOFF2), desktop (OTF/TTF), and variable font files.', price: 38.00, originalPrice: 65.00, category: 'Fonts', fileUrl: 'https://example.com/download/modern-sans.zip', badge: 'New' },
  { name: 'Elegant Serif Collection', image: 'https://images.unsplash.com/photo-1618367588411-d9a90fefa881?auto=format&fit=crop&q=80&w=800', description: '6 timeless serif font families with italic variants, ligatures, and stylistic alternates. Perfect for editorial design, book covers, luxury branding, and wedding invitations. OTF + TTF + WOFF2.', price: 42.00, originalPrice: 72.00, category: 'Fonts', fileUrl: 'https://example.com/download/elegant-serif.zip' },
  { name: 'Display & Decorative Font Bundle', image: 'https://images.unsplash.com/photo-1456081101716-74e616ab23d8?auto=format&fit=crop&q=80&w=800', description: '15 bold, eye-catching display fonts for posters, social media, packaging, and merch. Includes retro, grunge, outline, and 3D extrusion styles. Full commercial license for unlimited projects.', price: 29.00, originalPrice: 50.00, category: 'Fonts', fileUrl: 'https://example.com/download/display-fonts.zip', badge: 'Hot' },
  { name: 'Monospace Developer Fonts', image: 'https://images.unsplash.com/photo-1515879218367-8466d910auj9?auto=format&fit=crop&q=80&w=800', description: '5 beautifully crafted monospace fonts optimized for code editors and terminals. Features programming ligatures, powerline glyphs, and extended Unicode support. Variable font + static weights.', price: 19.00, originalPrice: 35.00, category: 'Fonts', fileUrl: 'https://example.com/download/mono-fonts.zip' },
  { name: 'Calligraphy & Lettering Kit', image: 'https://images.unsplash.com/photo-1596526131083-e8c633c948d2?auto=format&fit=crop&q=80&w=800', description: '12 stunning calligraphy and brush lettering fonts with alternates and swashes. Bundled with 50 pre-made quote overlays and ornament elements. Perfect for logos, greeting cards, and merchandise.', price: 26.00, originalPrice: 44.00, category: 'Fonts', fileUrl: 'https://example.com/download/calligraphy-kit.zip', badge: 'Bestseller' },

  // ── Code (5 new) ──
  { name: 'Vue.js Admin Dashboard', image: 'https://images.unsplash.com/photo-1517694712202-14dd9538aa97?auto=format&fit=crop&q=80&w=800', description: 'Production-ready Vue 3 + Vite admin panel with 50+ pages, Pinia state management, dark mode, role-based auth, and charting libraries (ApexCharts). Fully typed with TypeScript and includes API mock server.', price: 89.00, originalPrice: 149.00, category: 'Code', fileUrl: 'https://example.com/download/vue-admin.zip', badge: 'New' },
  { name: 'Flutter E-Commerce App', image: 'https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?auto=format&fit=crop&q=80&w=800', description: 'Cross-platform Flutter e-commerce app with product browsing, cart, checkout, order tracking, push notifications, and Firebase backend. Supports iOS and Android with a single codebase. 80+ screens.', price: 129.00, originalPrice: 219.00, category: 'Code', fileUrl: 'https://example.com/download/flutter-ecom.zip', badge: 'Featured' },
  { name: 'Node.js REST API Starter', image: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?auto=format&fit=crop&q=80&w=800', description: 'Production-grade Node.js REST API boilerplate with Express, MongoDB, JWT auth, rate limiting, input validation, file uploads, email service, and comprehensive Swagger documentation. Follows MVC pattern.', price: 59.00, originalPrice: 99.00, category: 'Code', fileUrl: 'https://example.com/download/node-api-starter.zip' },
  { name: 'Machine Learning Toolkit', image: 'https://images.unsplash.com/photo-1677442136019-21780ecad995?auto=format&fit=crop&q=80&w=800', description: '20 Jupyter notebooks covering classification, regression, NLP, image recognition, and recommendation systems using scikit-learn, TensorFlow, and PyTorch. Includes datasets, visualizations, and deployment guides.', price: 65.00, originalPrice: 110.00, category: 'Code', fileUrl: 'https://example.com/download/ml-toolkit.zip', badge: 'Hot' },
  { name: 'WordPress Theme Developer Kit', image: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&q=80&w=800', description: 'Build custom WordPress themes from scratch with this developer starter kit. Includes Gutenberg block templates, WooCommerce integration, customizer API setup, and child theme scaffolding. PHP 8.2+ compatible.', price: 45.00, originalPrice: 79.00, category: 'Code', fileUrl: 'https://example.com/download/wp-dev-kit.zip' },

  // ── Video (5 new) ──
  { name: 'YouTube Intro Templates', image: 'https://images.unsplash.com/photo-1611162616475-46b635cb6868?auto=format&fit=crop&q=80&w=800', description: '25 dynamic YouTube intro templates for After Effects and Premiere Pro. Includes glitch, neon, minimal, 3D text, and particle styles. Easy to customize with your logo and brand colors. 4K resolution.', price: 35.00, originalPrice: 59.00, category: 'Video', fileUrl: 'https://example.com/download/yt-intros.zip', badge: 'Bestseller' },
  { name: 'Wedding Film Overlays', image: 'https://images.unsplash.com/photo-1519741497674-611481863552?auto=format&fit=crop&q=80&w=800', description: '80+ dreamy wedding film overlays including light leaks, bokeh, lens flares, dust particles, and film burn effects. ProRes 4444 with alpha channel. Compatible with all major editing software.', price: 28.00, originalPrice: 48.00, category: 'Video', fileUrl: 'https://example.com/download/wedding-overlays.zip' },
  { name: 'Social Media Video Kit', image: 'https://images.unsplash.com/photo-1611162618071-b39a2ec055fb?auto=format&fit=crop&q=80&w=800', description: '100 animated social media templates for Instagram Reels, TikTok, and YouTube Shorts. Includes story templates, lower thirds, subscribe buttons, and call-to-action animations. Premiere Pro + After Effects.', price: 42.00, originalPrice: 69.00, category: 'Video', fileUrl: 'https://example.com/download/social-video-kit.zip', badge: 'Hot' },
  { name: 'Cinematic Drone Footage Pack', image: 'https://images.unsplash.com/photo-1473968512647-3e447244af8f?auto=format&fit=crop&q=80&w=800', description: '30 royalty-free 4K drone footage clips of breathtaking landscapes — mountains, beaches, forests, and cityscapes. Shot in LOG profile for maximum color grading flexibility. H.265 codec.', price: 59.00, originalPrice: 99.00, category: 'Video', fileUrl: 'https://example.com/download/drone-footage.zip', badge: 'New' },
  { name: 'Animated Title Pack', image: 'https://images.unsplash.com/photo-1536240478700-b869070f9279?auto=format&fit=crop&q=80&w=800', description: '60 professionally animated title templates for Premiere Pro and DaVinci Resolve. Categories include minimal, cinematic, corporate, creative, and broadcast styles. Easily change fonts, colors, and timing.', price: 32.00, originalPrice: 52.00, category: 'Video', fileUrl: 'https://example.com/download/title-animations.zip' },

  // ──────────────────────────────────────────────────
  //  BATCH 3 — 35 more products (5 per category)
  // ──────────────────────────────────────────────────

  // ── Templates (5 more) ──
  { name: 'Online Learning Platform UI', image: 'https://images.unsplash.com/photo-1501504905252-473c47e087f8?auto=format&fit=crop&q=80&w=800', description: 'Complete LMS (Learning Management System) UI kit with 75+ screens for course catalogs, video lessons, quizzes, progress tracking, certificates, and instructor dashboards. Figma + Sketch files with auto-layout.', price: 79.00, originalPrice: 139.00, category: 'Templates', fileUrl: 'https://example.com/download/lms-ui-kit.zip', badge: 'New' },
  { name: 'Healthcare & Telemedicine UI Kit', image: 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?auto=format&fit=crop&q=80&w=800', description: 'HIPAA-inspired telemedicine UI kit with patient registration, appointment scheduling, video consultation, prescription management, and health record views. 55 responsive screens in Figma.', price: 65.00, originalPrice: 109.00, category: 'Templates', fileUrl: 'https://example.com/download/healthcare-ui.zip' },
  { name: 'Real Estate Listing Template', image: 'https://images.unsplash.com/photo-1560518883-ce09059eeffa?auto=format&fit=crop&q=80&w=800', description: 'Property listing website template with map integration layouts, virtual tour placeholders, mortgage calculator UI, agent profiles, and neighborhood guides. Responsive HTML/CSS + Figma source.', price: 42.00, originalPrice: 69.00, category: 'Templates', fileUrl: 'https://example.com/download/realestate-template.zip' },
  { name: 'Event & Conference Template', image: 'https://images.unsplash.com/photo-1540575467063-178a50c2df87?auto=format&fit=crop&q=80&w=800', description: 'Multi-page event website template with speaker profiles, schedule timeline, ticket booking UI, sponsor showcases, and live stream layouts. Includes countdown timer and interactive agenda components.', price: 33.00, originalPrice: 55.00, category: 'Templates', fileUrl: 'https://example.com/download/event-template.zip', badge: 'Featured' },
  { name: 'Travel & Booking App UI', image: 'https://images.unsplash.com/photo-1488646953014-85cb44e25828?auto=format&fit=crop&q=80&w=800', description: 'Full travel booking app UI kit with flight search, hotel listings, trip itineraries, reviews, payment flows, and destination guides. 90+ mobile screens with dark and light themes. Figma only.', price: 55.00, originalPrice: 95.00, category: 'Templates', fileUrl: 'https://example.com/download/travel-app-ui.zip', badge: 'Hot' },

  // ── Graphics (5 more) ──
  { name: 'Infographic Elements Pack', image: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&q=80&w=800', description: '250+ infographic elements including charts, timelines, process flows, comparison tables, maps, and data visualization components. AI + EPS + PNG formats. Perfect for presentations and reports.', price: 28.00, originalPrice: 48.00, category: 'Graphics', fileUrl: 'https://example.com/download/infographic-pack.zip', badge: 'New' },
  { name: 'Watercolor Texture Bundle', image: 'https://images.unsplash.com/photo-1579783902614-a3fb3927b6a5?auto=format&fit=crop&q=80&w=800', description: '100 high-resolution watercolor textures and washes in pastel, vibrant, and earthy palettes. Seamless tileable backgrounds at 6000×4000px. Includes Photoshop brushes and PNG overlays.', price: 21.00, originalPrice: 36.00, category: 'Graphics', fileUrl: 'https://example.com/download/watercolor-textures.zip' },
  { name: 'Neon Sign Creator Kit', image: 'https://images.unsplash.com/photo-1563207153-f403bf289096?auto=format&fit=crop&q=80&w=800', description: 'Create realistic neon sign effects with 30 pre-built neon text styles, 20 wall backgrounds, glow brushes, and tube elements. Photoshop PSD + Illustrator AI. Includes video tutorial.', price: 26.00, originalPrice: 42.00, category: 'Graphics', fileUrl: 'https://example.com/download/neon-creator.zip', badge: 'Hot' },
  { name: 'Minimal Line Art Icons', image: 'https://images.unsplash.com/photo-1611532736597-de2d4265fba3?auto=format&fit=crop&q=80&w=800', description: '400+ minimal line art icons across 20 categories — business, education, health, travel, food, tech, and more. Consistent 2px stroke weight. SVG, PNG (multiple sizes), and Figma component library.', price: 19.00, originalPrice: 32.00, category: 'Graphics', fileUrl: 'https://example.com/download/line-icons.zip', badge: 'Bestseller' },
  { name: 'Abstract Geometric Patterns', image: 'https://images.unsplash.com/photo-1558591710-4b4a1ae0f04d?auto=format&fit=crop&q=80&w=800', description: '60 seamless geometric patterns in modern color schemes. Includes Memphis, Art Deco, Bauhaus, and contemporary styles. Available as vector files (AI/SVG) and high-res PNGs. Commercial license included.', price: 16.00, originalPrice: 28.00, category: 'Graphics', fileUrl: 'https://example.com/download/geo-patterns.zip' },

  // ── Audio (5 more) ──
  { name: 'Acoustic Guitar Loops', image: 'https://images.unsplash.com/photo-1510915361894-db8b60106cb1?auto=format&fit=crop&q=80&w=800', description: '60 beautifully recorded acoustic guitar loops in various styles — fingerpicking, strumming, arpeggios, and percussive. Multiple tempos (80–140 BPM) and keys. WAV 24-bit, royalty-free for any project.', price: 17.00, originalPrice: 29.00, category: 'Audio', fileUrl: 'https://example.com/download/acoustic-loops.zip' },
  { name: 'Vocal Chops & Textures', image: 'https://images.unsplash.com/photo-1598653222000-6b7b7a552625?auto=format&fit=crop&q=80&w=800', description: '300+ processed vocal chops, ad-libs, stacks, and atmospheric vocal textures. Perfect for EDM, pop, and hip-hop productions. Includes dry and wet versions. Key-labeled for easy pitching.', price: 22.00, originalPrice: 38.00, category: 'Audio', fileUrl: 'https://example.com/download/vocal-chops.zip', badge: 'New' },
  { name: 'Cinematic Transition SFX', image: 'https://images.unsplash.com/photo-1485846234645-a62644f84728?auto=format&fit=crop&q=80&w=800', description: '150 cinematic transition sound effects — risers, downers, whooshes, impacts, stingers, and sub drops. Essential for video editors, trailer makers, and motion designers. WAV 48kHz/24-bit.', price: 26.00, originalPrice: 42.00, category: 'Audio', fileUrl: 'https://example.com/download/cine-transitions.zip', badge: 'Featured' },
  { name: 'Piano Melodies Collection', image: 'https://images.unsplash.com/photo-1520523839897-bd0b52f945a0?auto=format&fit=crop&q=80&w=800', description: '40 emotional piano melodies and chord progressions recorded on a Steinway grand. Genres include classical, cinematic, lo-fi, and ambient. MIDI files + WAV stems included for full creative control.', price: 20.00, originalPrice: 34.00, category: 'Audio', fileUrl: 'https://example.com/download/piano-melodies.zip' },
  { name: 'Electronic Music Producer Pack', image: 'https://images.unsplash.com/photo-1563330232-57114bb0823c?auto=format&fit=crop&q=80&w=800', description: 'All-in-one electronic music production bundle with 800+ samples: synth leads, bass patches, arps, pads, FX, and drum hits. Covers house, techno, trance, dubstep, and future bass. Ableton/FL Studio ready.', price: 49.00, originalPrice: 85.00, category: 'Audio', fileUrl: 'https://example.com/download/edm-producer.zip', badge: 'Hot' },

  // ── Photography (5 more) ──
  { name: 'Travel Photography Presets', image: 'https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?auto=format&fit=crop&q=80&w=800', description: '20 vibrant travel photography presets for Lightroom that bring out the best in landscapes, architecture, and adventure shots. Includes tropical, desert, urban, and alpine variations. Mobile + Desktop.', price: 15.00, originalPrice: 26.00, category: 'Photography', fileUrl: 'https://example.com/download/travel-presets.zip', badge: 'New' },
  { name: 'Portrait Retouching Toolkit', image: 'https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?auto=format&fit=crop&q=80&w=800', description: 'Professional portrait retouching kit with 15 Lightroom presets, 10 Photoshop actions for skin smoothing, teeth whitening, eye enhancement, and dodge & burn workflows. Includes video walkthrough.', price: 24.00, originalPrice: 42.00, category: 'Photography', fileUrl: 'https://example.com/download/portrait-toolkit.zip', badge: 'Bestseller' },
  { name: 'Vintage Film Emulation Pack', image: 'https://images.unsplash.com/photo-1495745966610-2a67f2297e5e?auto=format&fit=crop&q=80&w=800', description: '25 film emulation presets replicating iconic analog film stocks — Kodak Portra, Fuji Superia, Ilford HP5, Cinestill 800T, and more. Adds authentic grain, halation, and color shifts. LR + ACR compatible.', price: 19.00, originalPrice: 32.00, category: 'Photography', fileUrl: 'https://example.com/download/film-emulation.zip' },
  { name: 'Product Photography Backgrounds', image: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&q=80&w=800', description: '80 clean, high-resolution background images for product photography and e-commerce listings. Includes marble, wood, fabric, concrete, and solid color surfaces at 8000×5000px. Commercial license.', price: 22.00, originalPrice: 38.00, category: 'Photography', fileUrl: 'https://example.com/download/product-backgrounds.zip' },
  { name: 'Night & Astrophotography Presets', image: 'https://images.unsplash.com/photo-1519681393784-d120267933ba?auto=format&fit=crop&q=80&w=800', description: '12 specialized presets for night sky, Milky Way, aurora, and long-exposure photography. Enhances star clarity, reduces noise, and boosts nebula colors. Works with RAW files in Lightroom Classic and CC.', price: 16.00, originalPrice: 27.00, category: 'Photography', fileUrl: 'https://example.com/download/astro-presets.zip', badge: 'Hot' },

  // ── Fonts (5 more) ──
  { name: 'Retro & Groovy Font Pack', image: 'https://images.unsplash.com/photo-1572044162444-ad60f128bdea?auto=format&fit=crop&q=80&w=800', description: '10 funky retro-inspired fonts capturing 60s, 70s, and 80s vibes. Includes psychedelic, disco, bubble, and groovy styles. Perfect for posters, album art, and vintage branding. OTF + TTF + WOFF2.', price: 24.00, originalPrice: 40.00, category: 'Fonts', fileUrl: 'https://example.com/download/retro-fonts.zip', badge: 'New' },
  { name: 'Minimal UI Font Family', image: 'https://images.unsplash.com/photo-1555421689-d68471e189f2?auto=format&fit=crop&q=80&w=800', description: 'A carefully designed geometric sans-serif family with 9 weights, italics, and condensed variants (36 styles total). Optimized for screen readability with large x-height and open counters. Variable font included.', price: 48.00, originalPrice: 85.00, category: 'Fonts', fileUrl: 'https://example.com/download/minimal-ui-font.zip', badge: 'Featured' },
  { name: 'Blackletter & Gothic Collection', image: 'https://images.unsplash.com/photo-1457369804613-52c61a468e7d?auto=format&fit=crop&q=80&w=800', description: '8 blackletter and gothic font families ranging from traditional Fraktur to modern interpretations. Includes ornamental capitals, alternate glyphs, and decorative swashes. OTF + TTF formats.', price: 21.00, originalPrice: 36.00, category: 'Fonts', fileUrl: 'https://example.com/download/blackletter-fonts.zip' },
  { name: 'Stencil & Military Font Set', image: 'https://images.unsplash.com/photo-1504639725590-34d0984388bd?auto=format&fit=crop&q=80&w=800', description: '6 bold stencil and military-style fonts with distressed and clean versions. Great for packaging, gaming, sports branding, and industrial design. Includes multi-language support and tabular figures.', price: 17.00, originalPrice: 29.00, category: 'Fonts', fileUrl: 'https://example.com/download/stencil-fonts.zip' },
  { name: 'Rounded & Friendly Font Bundle', image: 'https://images.unsplash.com/photo-1516414447565-b14be0adf13e?auto=format&fit=crop&q=80&w=800', description: '7 soft, rounded font families perfect for children\'s brands, apps, and friendly UI designs. Features playful alternates, emojis as glyphs, and multilingual character sets. 5 weights each. OTF + WOFF2.', price: 32.00, originalPrice: 55.00, category: 'Fonts', fileUrl: 'https://example.com/download/rounded-fonts.zip', badge: 'Hot' },

  // ── Code (5 more) ──
  { name: 'Laravel API Boilerplate', image: 'https://images.unsplash.com/photo-1555949963-ff9fe0c870eb?auto=format&fit=crop&q=80&w=800', description: 'Production-ready Laravel 11 REST API starter with Sanctum auth, role permissions (Spatie), file uploads to S3, queue workers, email notifications, and Swagger auto-documentation. Docker Compose included.', price: 69.00, originalPrice: 119.00, category: 'Code', fileUrl: 'https://example.com/download/laravel-api.zip', badge: 'New' },
  { name: 'React Native Social App', image: 'https://images.unsplash.com/photo-1611162617474-5b21e879e113?auto=format&fit=crop&q=80&w=800', description: 'Full-featured social media app built with React Native and Firebase. Includes user profiles, photo/video posts, stories, real-time chat, push notifications, and an explore feed. 100+ screens.', price: 139.00, originalPrice: 229.00, category: 'Code', fileUrl: 'https://example.com/download/rn-social-app.zip', badge: 'Bestseller' },
  { name: 'Django E-Commerce Platform', image: 'https://images.unsplash.com/photo-1504868584819-f8e8b4b6d7e3?auto=format&fit=crop&q=80&w=800', description: 'Complete Django 5 e-commerce platform with product catalog, cart, Stripe/PayPal checkout, order management, admin panel, SEO tools, and multi-vendor support. Deployed with Docker + Nginx + Gunicorn.', price: 99.00, originalPrice: 169.00, category: 'Code', fileUrl: 'https://example.com/download/django-ecom.zip' },
  { name: 'TypeScript Utility Library', image: 'https://images.unsplash.com/photo-1542831371-29b0f74f9713?auto=format&fit=crop&q=80&w=800', description: '200+ battle-tested TypeScript utility functions for arrays, objects, strings, dates, validation, and async operations. Tree-shakeable, zero dependencies, 100% test coverage. Published-ready with Changesets.', price: 29.00, originalPrice: 49.00, category: 'Code', fileUrl: 'https://example.com/download/ts-utils.zip' },
  { name: 'DevOps CI/CD Template Pack', image: 'https://images.unsplash.com/photo-1667372393119-3d4c48d07fc9?auto=format&fit=crop&q=80&w=800', description: '30 production-ready CI/CD pipeline templates for GitHub Actions, GitLab CI, and Jenkins. Covers Node.js, Python, Go, Docker, Kubernetes deployments, and Terraform infrastructure. Includes secrets management guides.', price: 39.00, originalPrice: 65.00, category: 'Code', fileUrl: 'https://example.com/download/cicd-templates.zip', badge: 'Hot' },

  // ── Video (5 more) ──
  { name: 'Glitch & VHS Effect Pack', image: 'https://images.unsplash.com/photo-1550745165-9bc0b252726f?auto=format&fit=crop&q=80&w=800', description: '40 glitch, VHS, CRT, and distortion effect overlays for videos. Includes scanlines, RGB splits, static noise, and tape rewinding effects. 4K ProRes with alpha channel. Works with any editor.', price: 24.00, originalPrice: 40.00, category: 'Video', fileUrl: 'https://example.com/download/glitch-vhs.zip', badge: 'New' },
  { name: 'Corporate Presentation Video Kit', image: 'https://images.unsplash.com/photo-1557804506-669a67965ba0?auto=format&fit=crop&q=80&w=800', description: '35 clean, professional video templates for corporate presentations, pitch decks, and product launches. Includes animated charts, team introductions, and call-to-action slides. After Effects + Premiere Pro.', price: 45.00, originalPrice: 75.00, category: 'Video', fileUrl: 'https://example.com/download/corporate-video.zip', badge: 'Featured' },
  { name: 'Particle & Dust Overlays', image: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&q=80&w=800', description: '50 organic particle and floating dust overlays shot practically against black backgrounds. Includes bokeh particles, embers, snow, rain, and magical sparkles. 4K 60fps MP4 + ProRes.', price: 22.00, originalPrice: 38.00, category: 'Video', fileUrl: 'https://example.com/download/particle-overlays.zip' },
  { name: 'Podcast Video Template Kit', image: 'https://images.unsplash.com/photo-1590602847861-f357a9332bbc?auto=format&fit=crop&q=80&w=800', description: 'Turn your podcast into engaging video content with 20 animated layouts for solo hosts, interviews, and panels. Includes audiogram waveforms, chapter markers, and branded end screens. Premiere Pro MOGRT files.', price: 30.00, originalPrice: 49.00, category: 'Video', fileUrl: 'https://example.com/download/podcast-video.zip', badge: 'Hot' },
  { name: 'Fitness & Workout Video Pack', image: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?auto=format&fit=crop&q=80&w=800', description: '25 energetic video templates for fitness brands — workout timers, exercise overlays, before/after splits, progress trackers, and motivational quote animations. Fully customizable in After Effects.', price: 33.00, originalPrice: 55.00, category: 'Video', fileUrl: 'https://example.com/download/fitness-video.zip' },
];

const seedData = async () => {
  try {
    await Product.deleteMany();
    await User.deleteMany();

    await Product.insertMany(products);

    await User.create({
      name: 'Admin Developer',
      email: 'admin@digihub.com',
      password: 'adminpassword123',
      isAdmin: true,
      isVerified: true,
    });

    console.log('✅ Database Seeded with 94 products!');
    process.exit();
  } catch (error) {
    console.error(`❌ Error: ${error.message}`);
    process.exit(1);
  }
};

seedData();
